# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        oauth:
            id: hwi_oauth.user.provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        main:
#            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: hwi_oauth_connect
                check_path: hwi_oauth_connect
            logout: true
            access_denied_url: hwi_oauth_connect
            oauth:
                resource_owners:
                    qq: qq_login
                login_path: hwi_oauth_connect
                failure_path:   hwi_oauth_connect
                oauth_user_provider:
                    service: hwi_oauth.user.provider
    access_control:
        - { path: ^/news/(new|(\d+\/edit)), roles: IS_AUTHENTICATED_FULLY }