# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
<<<<<<< HEAD
#        oauth:
#            id: hwi_oauth.user.provider
        fos_user:
            id: fos_user.user_provider.username
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 10
    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPPER_ADMIN:  ROLE_ADMIN
=======
        oauth:
            id: hwi_oauth.user.provider

>>>>>>> ef3341ce1d889427c0b61466372d7436132ca23f
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        main:
#            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
        secured_area:
            pattern: ^/
            anonymous: ~
<<<<<<< HEAD

            form_login:
                provider: fos_user
                csrf_provider: form.csrf_provider
            logout: true

#            access_denied_url: hwi_oauth_connect
=======
            form_login:
                login_path: hwi_oauth_connect
                check_path: hwi_oauth_connect
            logout: true
            access_denied_url: hwi_oauth_connect
>>>>>>> ef3341ce1d889427c0b61466372d7436132ca23f
            oauth:
                resource_owners:
                    qq: qq_login
                login_path: hwi_oauth_connect
                failure_path:   hwi_oauth_connect
                oauth_user_provider:
<<<<<<< HEAD
#                    service: hwi_oauth.user.provider
                    service: hwi_oauth.user.provider.fosub_bridge
=======
                    service: hwi_oauth.user.provider
>>>>>>> ef3341ce1d889427c0b61466372d7436132ca23f
    access_control:
        - { path: ^/news/(new|(\d+\/edit)), roles: IS_AUTHENTICATED_FULLY }